[project]
name = "pysnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numba>=0.60.0",
    "numpy>=2.0.2",
    "scipy>=1.14.1",
]
